### ISSUE TITLE
Use Shellfu coding style for Bash API

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/preupgrade-assistant#102]
There aren't many coding styles for Bash, which (since I write a lot
id Bash) is the reason I had to create my own as part of Shellfu
project, so if I may humbly propose:

    http://file.vornet.cz/tmp/shellfu-style.html

Pros:

 *  Not big (~400-500 sparse lines), plus not all would be relevant
    to common.sh --- mainly the Docstrings section is relevant.

 *  Part of Shellfu project is a tool `shellfu-doc` which can help
    export docs out of the code that uses this style.

    (The tool is not finished --- it can't parse variable docs but
    it's a top priority to be done.)

 *  Really simple, does not get in the way.

 *  Quite similar to what's already used in common.sh.

Cons:

 *  Not 100% complete yet (although I don't expect it to grow much)

 *  Used only by me so far :) ... on multiple projects, though...

**Comment by phracek** [comment]
What about to send a PR, If you are familiar with it?
I guess, It will help us a lot. Do you have a time to do it?

**Comment by AloisMahdal** [comment]
if this issue gets approved, I will send PR.

**Comment by praiskup** [comment]
> http://file.vornet.cz/tmp/shellfu-style.html

One issue I consider misleading, use 'case $var in' not 'case "$var" in'.  There
is no reason to use double quotes.

**Comment by praiskup** [comment]
Also 'something_with "$line"' instead of 'something_with $line'.

**Comment by praiskup** [comment]
s/test -n "item"/test -n "$item"/

**Comment by AloisMahdal** [comment]
@praiskup thanks a lot for feedback; I'll reflect that in upstream (sorry, not released yet) guide and update the HTML.

However, as was pointed out elsewhere, lot of things in the guide are irrelevant in preupgrade-assistant context (eg. the `shellfu import` stuff), so rest assured it won't be applied completely. For now we've agreed with @phracek that I'll apply just the Documentation part; (maybe I'll add the variable definition conventions as well in other PR).
