### ISSUE TITLE
weird behaviour around dirname of set of modules

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant#124]
Functionality of PA is really bounded to name of directory, like RHEL6_7. For different names - format of name - in better cases print error message and ends. However, for another cases it will not print any troubles and another processing and results are really wrong.

E.g.:
- RHEL6_7-results - processing ends OK, however some replace_holder strings in results.html are not replaced (like *_SOLUTION_TEXT)
- 6_7 - contents end as not applicable but any message about name of directory, which causes this
  .... etc

At least PA have to check correctly if everything is OK and print relevant error message and end with error when there is used name of directory, which affects significantly another processing and required format of name must be documented.

However, some behaviour mentioned above shouldn't be really affected by the name of directory.

**Comment by phracek** [comment]
I see the point. But module dirname should contain at least numbers.
And w/o numbers it should work too. I will incorporate the change soon.

**Comment by phracek** [comment]
@AloisMahdal @pirat89 What about to have only dirname or whatever user specifies and inside dirname a file which specifies an upgrade path?
But definitely we should have specified an upgrade path.

**Comment by AloisMahdal** [comment]
IMO: Anything that defines the upgrade path should be inside the folder; the folder *name* should not bear any information whatsoever.

For meta-data, a file or set of files seems an obvious solution.  The format is not really important as it's wholly managed by automated tools (we don't expect path devels/users to edit or even see the data; this also means we can always change the format later) so I'd go for something dead simple.

I hope I have answered your question.

**Comment by phracek** [comment]
Yeah, I will implemented in the next release cycle and make sense to me.

**Comment by phracek** [comment]
This issue will be solved by PR #148

**Comment by bocekm** [comment]
The change is implemented in https://github.com/upgrades-migrations/preupgrade-assistant/pull/233.
Resolves rhbz: https://bugzilla.redhat.com/show_bug.cgi?id=1412539.

**Comment by AloisMahdal** [comment]
@bocekm, a little correction: rhbz#1412539, is a "meta-bug" and suggests several changes (some even in modules). There is no direct downstream counterpart to this change; I planned to file each bug once we agree which parts we want to do.

**Comment by bocekm** [comment]
Another two PRs that addresses this issue: PR https://github.com/upgrades-migrations/preupgrade-assistant/issues/280 and https://github.com/upgrades-migrations/preupgrade-assistant/issues/286

**Comment by bocekm** [comment]
Other relevant PRs: https://github.com/upgrades-migrations/preupgrade-assistant/pull/287, https://github.com/upgrades-migrations/preupgrade-assistant/pull/297
The Preupgrade Assistant now requires properties.ini file in which there are source and destination system version numbers specified. Name of the module set directory can be arbitrary.
