### ISSUE TITLE
function for exit priority results

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant#125]
Just idea that some function which provides some logic around exit codes (results) of modules would be fine. Like: when You set once $RESULT_ERROR, probably You should not exit later with $RESULT_PASS, etc.

```bash
# just example for easier explanation
ret=$RESULT_PASS
set_result() {
  case $1 in
    $RESULT_ERROR) ret=$1 ;;
    $RESULT_FAIL)  [ $ret -ne $RESULT_ERROR ] && ret=$1 ;;
    $RESULT_FIXED) [ $ret -ne $RESULT_ERROR ] && [ $ret -ne $RESULT_FAIL ] && ret=$1 ;;
  esac
}
```

It's not probably suitable to API for various reasons, but
 * it could appear in some template
 * it can be commented in API scripts (that means stored there as comment, so will not be available through API) as it can be used by users when they want it in own modules
 * it can be mentioned in documentation like tips

But using in templates seems as the best option for me.  What do You think about it?

**Comment by phracek** [comment]
Personally, I don't see a benefit.

instead of calling exit_error we will call a function set_result RESULT_ERROR.

**Comment by pirat89** [comment]
Benefit is: when you set for something ERROR, you will not overwrite it by FIXED or FAILED later - jst because you don't want to leave processing of the script immadiately and print other possible errors or results yet. But final result should be still error. Using of variables makes still sense in some cases even when we have functions for exits too.

For me it seems useful at least in template.

**Comment by AloisMahdal** [comment]
I don't understand: if you use exit_error, the module exits so there's no way for you to change it later.

Also I would prefer avoiding adding anything more than necessary into any templates (let alone API or comments somewhere).

By the way, I have a different proposal (in my head, and outside scope of this ticket), that I believe would solve what you had in mind, plus other problems, though: In nutshell, no exit statuses at all but instead a dedicated file where status is written using dedicated API (could be called `set_status`).  That would solve problems such as: script fails during initialization, unexpected bash/python crash, `exit_*` is just not called for some reason... As side effect it would also allow us to apply usage error handling such as what you propose.

**Comment by pirat89** [comment]
> I don't understand: if you use exit_*, the module exits so there's no way for you to change it later.

@AloisMahdal  Just look better at code and comments above :-) There is not used any exit_* ;-)

> 
By the way, I have a different proposal (in my head, and outside scope of this ticket), that I believe would solve what you had in mind, plus other problems, though: In a nutshell: no exit statuses at all but instead a dedicated file where status is written using dedicated API (could be called set_status). That would solve problems such as: script fails during initialization, unexpected bash/python crash, exit_* is just not called for some reason... As side effect it would also allow us to apply usage error handling such as what you propose.

Yeah, something like that seems good to me. Just I think that this could be resolved later, when we will have changed exit+risk evaluation, because of regression. But put this under ice for now.

**Comment by AloisMahdal** [comment]
> @AloisMahdal Just look better at code and comments above :-) There is not used any exit_* ;-)

Currently calling `exit_*` (and risk, sometimes) is mandatory part of setting the result.  From your snippet and comments I understood that you're trying to solve problem of double setting (eg. fail then pass).

My point was: since `exit_*` ends the code, there's no way that can happen twice in a module, i.e. the problem does not exist.  Unless I'm missing something.

**Comment by pirat89** [comment]
But here is not called exit_* function anywhere in the code and there is nothing solved twice. You will calll
```bash
exit $ret
```
at the end of script, as this was original design (and still used in majority scripts). Or you can imagine that there will be used something like that at the and, becase we will want using of exit_* functions:
```
case $ret in
  <value1>)  <exit_1> ;;
  <value2>)  <exit_2> ;;
  <value3>)  <exit_3> ;;
esac
```

But still it is about, that when you set e.g. log_high_risk and somewhere else you fix something, you have to ends with exit_failed instead of exit_fixed. And the function guard this error, which is one of the most frequent errors in check scripts I have fixed and fix in new check scripts.

Yes, this will be obsoleted when we will leave risk+exit combination. Or there is still some misunderstanding from my side what about you are talking.
