### ISSUE TITLE
Module API compatibility checks

### ISSUE THREAD

**Issue by bocekm** [upgrades-migrations/preupgrade-assistant#166]
Implement versioning of the module API, both shell and python, together with API compatibility checks:
 - a module would have information for which API version it has been written
 - preupg would have information about the current API version and also a list of API versions with which the current API version is backward compatible
 - a module wouldn't be executed if the API version for which it has been written is not the current one OR is not in the list of the backward compatible APIs

**Comment by AloisMahdal** [comment]
This seems to me as duplicate of issue #100

**Comment by bocekm** [comment]
Correct. It's a duplicate to [#100](https://github.com/upgrades-migrations/preupgrade-assistant/issues/100).
