### ISSUE TITLE
bad error formatting when upgrade paths are missing

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/preupgrade-assistant#184]
When modules are missing, preupg shows message about it.  The message has broken formatting, though:

    [0 root@qeos-244 preupgrade-assistant]# preupg
    No handlers could be found for logger "preupgrade-assistant-debug"
    There were no modules found in the /usr/share/preupgrade directory.         If you would like to use this tool, you have to install some.
    [0 root@qeos-244 preupgrade-assistant]# 

Notice that the "There were no modules..." message is badly formatted.

This is from current master (65f3ac7).

**Comment by bocekm** [comment]
Fixed in https://github.com/upgrades-migrations/preupgrade-assistant/commit/628f2c108fab26a8b4bbbecf073b91dd8ca90f8a and released in Preupgrade Assistant v2.3.1
