### ISSUE TITLE
Catch global tracebacks in preupg binary

### ISSUE THREAD

**Issue by phracek** [upgrades-migrations/preupgrade-assistant#193]
We have modified manual page by Pull Request #192 .
Unfortunately exit 1 is also return values caused by tracebacks.
We should detect tracebacks caused by exceptions like IndexError, ValueError and stuff like that.

**Comment by bocekm** [comment]
Fixed by https://github.com/upgrades-migrations/preupgrade-assistant/commit/376a4de2e9c2ac81ac2934d3d6c6870d0289a5ab. All internal errors are caught in preupg binary and new return code is returned (30 .. settings.ReturnValues.INTERNAL_EXCEPTION).
