### ISSUE TITLE
[RFE] Support Python 3

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant#223]
One of the incompatibilities in Preupgrade Assistant is usage of argparse vs. optparse - details below:

On older system is only optparse available, which is deprecated already. This can be simply handled
in the way like (pseudocode):
```python
try:
    import argparse as cmdParser
except:
    import optparse as cmdParser
```
The rest of the code can be easily refactore to use cmdParser on few places.

**Comment by bocekm** [comment]
We do not currently plan to refactor the Preupgrade Assistant code to support Python 3. On operating systems where the Preupgrade Assistant is currently used, Python 2 is the default.
