### ISSUE TITLE
postmigrate (and others) directory is not provided in API

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant#224]
PA doesn't provide API to work with all directories which are part of the tarball and
have special usability for modules.

**Comment by AloisMahdal** [comment]
I don't think I understand.  The tarball is product of PA, modules can't possibly have chance to work with it; so what dso you mean by "directories which are part of the tarball"?

What is the issue here?

**Comment by pirat89** [comment]
.. these are directories like kickstart, podupgrade.d, cleanconf, ..... modules are quired to put something into this directories and this has to be hardcoded usually now. That's wront, isn't it?

**Comment by bocekm** [comment]
@pirat89 please provide full list of directories that are missing in API. I or @MajoDurco will add them there.

**Comment by bocekm** [comment]
Basically, the directories are in settings.py -> preupgrade_dirs, except _common_ and _hooks_.

**Comment by pirat89** [comment]
Resolved by PR https://github.com/upgrades-migrations/preupgrade-assistant/pull/363
