### ISSUE TITLE
Update crossarch_migration_support_check.patch to allow custom contents

### ISSUE THREAD

**Issue by bocekm** [upgrades-migrations/preupgrade-assistant#279]
Currently the [crossarch_migration_support_check.patch](https://github.com/upgrades-migrations/preupgrade-assistant/blob/master/packaging/sources/crossarch_migration_support_check.patch) requires proprietary data from the package _preupgrade-assistant-el6toel7_ (because of `/root/preupgrade/RHEL6_7/common/release_version` file) and _preupgrade-assistant-el6toel7-data_ (because of `/root/preupgrade/RHEL6_7/common/<src_arch>-<dst_arch>` folder). That shouldn't be happening because Preupgrade Assistant should be able to run with a custom user-created module set, i.e. without the proprietary data.

**Comment by AloisMahdal** [comment]
This is obsoleted by #314, which replaces the currently used method with another one,  removing the patch completely (ie. moving the relevant code to module set, hence [modules' #12][1]).

  [1]: https://github.com/upgrades-migrations/preupgrade-assistant-modules/pull/12
