### ISSUE TITLE
preupgrade-content-creator is broken

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/preupgrade-assistant#286]
As of current master (using internal build `2.4.4-1.201707271409Z.el6_8`), preupg-content-creator is completely broken; it will die at first question, no matter what I type in (even if it's exactly the same string as the error message suggests---a hack that does work with released version).

    # preupg-content-creator
    Specify the upgrade path (like RHEL6_7) where the module will be stored: FOO
    The scenario 'FOO' is not valid.
    It has to be like RHEL6_7 or CentOS7_RHEL7.
    # preupg-content-creator
    Specify the upgrade path (like RHEL6_7) where the module will be stored: RHEL6_7
    The scenario 'RHEL6_7' is not valid.
    It has to be like RHEL6_7 or CentOS7_RHEL7.
    # preupg-content-creator
    Specify the upgrade path (like RHEL6_7) where the module will be stored: CentOS7_RHEL7 
    The scenario 'CentOS7_RHEL7' is not valid.
    It has to be like RHEL6_7 or CentOS7_RHEL7.
    # 

(I suspect PR #233.)

**Comment by AloisMahdal** [comment]
Note that this blocks downstream testing of other PRs that are based on current master; I have no way to create mock modules now.

**Comment by MajoDurco** [comment]
Yes, you are right. It's caused with #233. I'll try to fix it ASAP.

**Comment by MajoDurco** [comment]
#287
