### ISSUE TITLE
properties.ini is searched at wrong path

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/preupgrade-assistant#312]
When using custom generated module set, preupg fails on missing `properties.ini`. However, the file is present at correct place.  From the error message, one can see that the path is just incorrect:

    properties.ini file not found inside /usr/share/preupgrade/FOO directory

(the real path is somewhere deep inside /tmp).

Version: preupgrade-assistant-2.4.4-0.201708291711Z.PR281

**Comment by bocekm** [comment]
@AloisMahdal, what do you mean byt "correct place"? Your custom generated module set is place somewhere else than `/usr/share/preupgrade/FOO`?
By the way, when you mention _/tmp_ it reminds me this fix: PR https://github.com/upgrades-migrations/preupgrade-assistant/pull/297 which is already in master (however build for PR #281 does not contain this fix).

**Comment by AloisMahdal** [comment]
>  what do you mean byt "correct place"?

My module is at path generated by mktemp, ie. I'm calling preupg with something like `preupg -c /tmp/tmp.XXXXXXX/FOO/all-xcddf.xml`.  */usr/share/preupgrade/FOO* doees not exist, nor is any module set installed.

**Comment by bocekm** [comment]
I fear you used the PR https://github.com/upgrades-migrations/preupgrade-assistant/pull/281 build that wasn't rebased with master. It's fixed by PR #297 which is already in master. I've tried your scenario and it works with the latest master build (I used ipu 0.1.0 for it and it works great :1st_place_medal:).
