### ISSUE TITLE
riskcheck will not run without upgrade path at /usr

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/preupgrade-assistant#320]
Importing rhbz#1372090.  Verified with preupgrade-assistant-2.4.4-0.201709220805Z.PR311.el6_8.noarch; it's still affected.

---

Description of problem
----------------------

It's possible to generate assessment without upgrade path installed at /usr/share, but it's not possible to use --riskcheck to verify this assessment: preupg will complain that upgrade path is not installed and exit with status 20.

Version-Release number of selected component
--------------------------------------------

preupgrade-assistant-2.1.9-1.el6

How reproducible
----------------

Always

Steps to Reproduce
------------------

 1. Create a custom upgrade path
 2. Run preupg with this path (--contents parameter)
 3. Run preupg --riskcheck --verbose

Actual results
--------------

Error is printed:

    There were no contents found in directory /usr/share/preupgrade. If you would like to use this tool, you have to install some

and exit status is 20.

Expected results
----------------

No error

Additional info
---------------

Note that --riskcheck (and other modes) documentation does not mention way to specify *which* result to check, so there's an underlying assumption that it's always the last one.

**Comment by bocekm** [comment]
--riskcheck functionality has been overhauled in https://github.com/upgrades-migrations/preupgrade-assistant/pull/218. I'll check whether it fixes your issue.

**Comment by bocekm** [comment]
Yay, still the same issue :(

**Comment by bocekm** [comment]
However `preupg --riskcheck -c /tmp/RHEL6_7/all-xccdf.xml --verbose` works. @AloisMahdal, so you think it's insufficient?
