### ISSUE TITLE
Fix running 3rd party modules

### ISSUE THREAD

**Issue by bocekm** [upgrades-migrations/preupgrade-assistant#324]
Currently, if anyone creates a module and puts it into the `/usr/share/preupgrade/RHEL6_7/3rdparty/` (or generally `/path/to/moduleset/3rdparty/`), this module is not executed.

**Comment by AloisMahdal** [comment]
The path suggests the module would be outside any module set.  IIUC our tools do not allow creating single module but rather a module set with one module, or add module into a module set.  In any case, the module set (and its properties.ini) determines context of that module.

IOW, it does not seem to me that we could even safely support this feature.

**Comment by pirat89** [comment]
The correct correct path is `/usr/share/preupgrade/RHEL6_7/3rdparty`

**Comment by bocekm** [comment]
Fixed by https://github.com/upgrades-migrations/preupgrade-assistant/pull/348
