### ISSUE TITLE
preupg --list-rules does not respect --contents

### ISSUE THREAD

**Issue by bocekm** [upgrades-migrations/preupgrade-assistant#325]
https://bugzilla.redhat.com/show_bug.cgi?id=1362708

**Comment by AloisMahdal** [comment]
(Importing original description.)

Description of problem
----------------------

When using preupg with a custom-generated upgrade path (using
preupg-xccdf-compose), the `--list-rules` command will not respect
`--contents` parameter

Instead; you'll get list of modules installed under /usr (--contents
is ignored).


Version-Release number of selected component
--------------------------------------------

preupgrade-assistant-2.1.8-2.el6


How reproducible
----------------

Always


Steps to Reproduce
------------------

 1. generate few modules usinf preupg-content-creator (provide
    same upgrade path name, ie. the first parameter)

 2. compile using `preupg-xccdf-compose DIR` (DIR will be same
    as the upgrade path name)

 3. `preupg --contents DIR/all-xccdf.xml --list-rules`


Actual results
--------------

You get list of rules installed under /usr (if any)


Expected results
----------------

List of just-created rules
