### ISSUE TITLE
--list-rules prints errors to stdout

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/preupgrade-assistant#333]
I've tried several types of `--list-rules` erros and all errors I've seen were reported to stdout instead of stderr:

 *  no `-c` and no installed sets,
 *  no `-c`, multiple installed sets, but no `-s` to choose one,
 *  `-c` poinred to invalid path.

**Comment by bocekm** [comment]
This problem stems from what I documented in https://github.com/upgrades-migrations/preupgrade-assistant/issues/315. IOW, refactoring logging functions will resolve this issue.
