### ISSUE TITLE
Using both -s and -c exits with 1

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/preupgrade-assistant#334]
Using both `-c` and `-s` results in preupg traceback and exit status 1.  However, that status is described in man page as:

> 1 - preupg works properly but at least one module finishes with NEEDS_ACTION result.

(I found this when testing `--list-rules` mode but it could apply to other modes as well.)

**Comment by pirat89** [comment]
This would be resolved with PR #330 by adding `try`+ `except` block inside `bin/preupg` - or generally, moving all content into existing try/catch block.
