### ISSUE TITLE
Unify the description of the Preupgrade Assistant

### ISSUE THREAD

**Issue by bocekm** [upgrades-migrations/preupgrade-assistant#338]
Currently there are four different versions of the Preupgrade Assistant description on five different places.

**[README.md](https://github.com/upgrades-migrations/preupgrade-assistant/blob/master/README.md)**:
_The Preupgrade Assistant is a framework designed to run the Preupgrade Assistant modules, which analyze the system for possible in-place upgrade limitations. It is based on a module system, with each module performing a separate test, checking for package removals, incompatible obsoletes, changes in libraries, name changes, or deficiencies in the compatibilities of certain configuration files. The data gathered by the Preupgrade Assistant can be used for migrating the system. It also has a possibility to process post-upgrade scripts that are provided by modules to finish more complex problems after the in-place upgrade. The Preupgrade Assistant utility is a [Red Hat Upgrade Tool](https://github.com/upgrades-migrations/redhat-upgrade-tool) prerequisite for completing a successful in-place upgrade to the next major version of Red Hat Enterprise Linux._

**Clouseau/Errata:**
_Preupgrade Assistant is a set of scripts and plug-ins that can assess your system before upgrading to the next major version of Red Hat Enterprise Linux. It checks for removed packages, packages with partially incompatible replacements, changes in libraries, users and groups, and various services. It then produces a report that assists you in performing the upgrade itself by outlining potential problem areas and offering suggestions about mitigating any possible incompatibilities. In addition, Preupgrade Assistant helps you install a new major release of Red Hat Enterprise Linux that is as similar as possible to your previous system. It also provides post-upgrade scripts, which will help you finish migration after the installation of a newer Red Hat Enterprise Linux release._

**[Spec file](https://github.com/upgrades-migrations/preupgrade-assistant/blob/master/packaging/preupgrade-assistant.spec) and [preupg.h2m](https://github.com/upgrades-migrations/preupgrade-assistant/blob/master/man/preupg.h2m) (used for generating man page):**
_Preupgrade Assistant analyses the system to assess the feasibility of upgrading the system to a new major version. Such analysis includes a check for removed packages, packages replaced by partially incompatible packages, changes in libraries, users and groups, and various other services. A report of this analysis can help admins with the system upgrade by identification of potential troubles and by mitigating some of the incompatibilities. The data gathered by Preupgrade Assistant can be used for the in-place upgrade or migration of the system, where the migration means a new system installation that retains as much of the old system setup as possible._

**[doc/README](https://github.com/upgrades-migrations/preupgrade-assistant/blob/master/doc/README)**:
_The Preupgrade Assistant performs an assessment of the system from the "upgradeability" point of view. Such an analysis includes checking for removed packages, packages replaced by partially incompatible packages, changes in libraries, users and groups and various services. The report of this analysis can help the admin with the in-place upgrade - by identifying potential troubles and by mitigating some of the incompatibilities. The data gathered by the Preupgrade Assistant can be used for "cloning" the system - a new, clean installation of the system, as close as possible to the old Red Hat Enterprise Linux setup. In addition, it provides some postupgrade scripts which are supposed to finish the migration after the installation of Red Hat Enterprise Linux 7 system. As the Preupgrade Assistant does not modify the assessed system directly (except storing information/logs), it is safe to use on any configuration. As the modules are not complete yet, a successful Preupgrade Assistant analysis does not necessarily mean that the in-place upgrade via redhat-upgrade-tool will succeed._

**Comment by bocekm** [comment]
My proposal follows (slightly updated README.md version). See **bold** for questionable wording.

_The Preupgrade Assistant is a framework designed to run the Preupgrade Assistant modules, which analyze the system for possible in-place upgrade limitations. It is based on a module system, with each module performing a separate test, checking for package removals, **incompatible obsoletes**, changes in libraries, users, groups, services or incompatibilities of command line options or configuration files. It is able to provide post-upgrade scripts to **finish** more complex problems after the system upgrade. Apart from performing the in-place upgrades, the Preupgrade Assistant is also capable of migrating the system. The Preupgrade Assistant utility is a Red Hat Upgrade Tool prerequisite for completing a successful in-place upgrade to the next major version of Red Hat Enterprise Linux._

**Also consider incorporating the following line:**
_It then produces a report that assists you in performing the upgrade itself by outlining potential problem areas and offering suggestions about mitigating any possible incompatibilities._

**Comment by jhornice** [comment]
The Preupgrade Assistant is a framework designed to run the Preupgrade Assistant modules, which analyze the system for possible in-place upgrade limitations. It is based on a modular system, with each module performing a separate test, checking for package removals, incompatible obsoletes, changes in libraries, users, groups, services, or incompatibilities of command line options or configuration files. It is able to provide post-upgrade scripts to finish more complex problems after the system upgrade. Apart from performing the in-place upgrades, the Preupgrade Assistant is also capable of migrating the system. It then produces a report, which assists you in performing the upgrade itself by outlining potential problem areas and by offering suggestions about mitigating any possible incompatibilities. The Preupgrade Assistant utility is a Red Hat Upgrade Tool prerequisite for completing a successful in-place upgrade to the next major version of Red Hat Enterprise Linux.

**Comment by jhornice** [comment]
I only don't understand "incompatible obsoletes"

**Comment by pirat89** [comment]
@jhornice: I can guess, that *obsoletes* means here set of packages, that replaces some original packages, but the replacements **are incompatible** with originals.

**Comment by jhornice** [comment]
ok, I will change it to "obsolete packages" then

**Comment by bocekm** [comment]
I guess this is can be considered the final version. I've changed the words in **bold**.

_The Preupgrade Assistant is a framework designed to run the Preupgrade Assistant modules, which analyze the system for possible in-place upgrade limitations. It is based on a modular system, with each module performing a separate test, checking for package removals, incompatible obsolete packages, changes in libraries, users, groups, services, or incompatibilities of command-line options or configuration files. It is able to **execute** post-upgrade scripts to **finalize** complex **tasks** after the system upgrade. Apart from performing the in-place upgrades, the Preupgrade Assistant is also capable of migrating the system. It then produces a report, which assists you in performing the upgrade itself by outlining potential problem areas and by offering suggestions about mitigating any possible incompatibilities. The Preupgrade Assistant utility is a Red Hat Upgrade Tool prerequisite for completing a successful in-place upgrade to the next major version of Red Hat Enterprise Linux._
