### ISSUE TITLE
error messages when stdin is redirected from pipe

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/preupgrade-assistant#343]
Running

    preupg <<<y

will produce multiple copies (4 with simple passing mock module) of this error message on stderr:

    stty: standard input: Inappropriate ioctl for device

This has been [known for some time][1]; I've verified this still appears with latest master (`2.5.0-1.201711021818Z`).

  [1]: https://bugzilla.redhat.com/show_bug.cgi?id=1331416#c3

**Comment by AloisMahdal** [comment]
@bocekm Could "we" make it in next milestone?  (We have it covered in tests for long time already.)   It keeps spamming our test logs so it would be nice to get rid of.

**Comment by bocekm** [comment]
I'll schedule it for the next milestone. We'll see what the priorities will be. We would accept even your PR ;)
