### ISSUE TITLE
Test whether ampersand is not being expanded multiple times

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant#37]
According to description of *test_amp_expand*, this test is probably wrong. I expects double call of *html_escape* or tests of **&amp** and other html entities directly - I expect that this is original idea of this test. Am I right Peter?

**Comment by phracek** [comment]
This test is running only one time. In preupg real time the function is run also only one time.

**Comment by pirat89** [comment]
Hmm, Ok, so that's wrong description of test?

**Comment by pirat89** [comment]
```
"""Test whether ampersand is not being expanded multiple times"""
```

**Comment by pirat89** [comment]
Ok better description of problem. From description of the test, should be checked if e.g. "&amp;" will be kept as **&amp;amp;** *(correct result)* or will be expanded again: **&amp;amp;amp;** *(incorrect result)*. And I think that really this should be tested too. Function shouldn't expand *safe ampersand*  used as html entity from my point of view.
