### ISSUE TITLE
python3 shebang

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant#56]
Python3 was announced for Fedora23 as default, however /usr/bin/python will be still for Python2. As I read we shouldn't use  shebang "#! /usr/bin/python" in our application, so we will do some harakiri.. or remove all shebang

**Comment by phracek** [comment]
It should be discussed with Python 3 team.
Before fixing we should find a right way how to solve it.

**Comment by pirat89** [comment]
Note from my memories of earlier discussion:
+ we need to set right shebang only in few scripts which are called from cmdline
+ here is suggested solution from bkabrda https://fedorahosted.org/fpc/ticket/327
+ so may we could kept in upstream repository current shebangs and just add suffix [2,3] by setup script

**Comment by bocekm** [comment]
We do not currently plan to refactor the Preupgrade Assistant code to support Python 3. On operating systems where the Preupgrade Assistant is currently used, Python 2 is the default.
