### ISSUE TITLE
Package list is not generated on Fedora

### ISSUE THREAD

**Issue by phracek** [upgrades-migrations/preupgrade-assistant#91]
preupg binary should generate a file /root/preupgrade/kickstart/package_files which contains a list of files
for %package generation.

On Fedora is different than on RHEL system. The list should not be hardcoded.

**Comment by pirat89** [comment]
Just note: this is solution just for packages files. However the file can be used to assign semantic for more files, not jsut package section. E.g. there can be added file which describes settings of firewall. 
What about something like:
```text
type <file> <...files>
```
e.g.:
```text
packages kept_packages kept_optional
firewall firewalld_rules
```

**Comment by phracek** [comment]
This issue is more or less for modules.

**Comment by bocekm** [comment]
We have decided to not be releasing modules for Fedora.
